Update deploy-to-pages.yml

diff --git a/.github/workflows/deploy-to-pages.yml b/.github/workflows/deploy-to-pages.yml
--- a/.github/workflows/deploy-to-pages.yml
+++ b/.github/workflows/deploy-to-pages.yml
@@ -1,35 +1,83 @@
-name: Deploy to GitHub Pages
+name: Deploy Next.js site to Pages
 
 on:
+  # Runs on pushes targeting the default branch
   push:
-    branches: [ "main" ]
+    branches: ['main']
 
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
   contents: read
   pages: write
   id-token: write
 
+# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
+concurrency:
+  group: 'pages'
+  cancel-in-progress: false
+
 jobs:
+  # Build job
   build:
+    name: Build Next.js Blog
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v3
+        
+      - name: Detect package manager
+        id: detect-package-manager
+        working-directory: ./flying-comet-homepage
+        run: |
+          if [ -f "${{ github.workspace }}/flying-comet-homepage/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/flying-comet-homepage/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
 
-    - name: Use Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '18.x'
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: '18'
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
 
-    - name: Install dependencies
-      run: npm ci
-      working-directory: ./flying-comet-homepage
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            ./flying-comet-homepage/.next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
 
-    - name: Build
-      run: npm run build
-      env:
-        CI: false      
-      working-directory: ./flying-comet-homepage
+      - name: Install dependencies
+        working-directory: ./flying-comet-homepage
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
 
+      - name: Build project assets
+        working-directory: ./flying-comet-homepage
+        run: ${{ steps.detect-package-manager.outputs.manager }} build
+
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v2
+        with:
+          path: ./flying-comet-homepage/out
+
+  # Deployment job
   deploy:
     environment:
       name: github-pages
@@ -40,5 +88,3 @@ jobs:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v2
-        with:
-          folder: ./flying-comet-homepage/build
